"""Base class, shared prompt, and local storage for image providers.

Real providers (OpenAI, Gemini) return raw image bytes rather than a hosted URL,
so generated bytes are written to a local directory and served by the FastAPI
app (see ``app/main.py``). The resulting URL is valid while the server runs.
"""

import logging
import os
import re
import uuid
from abc import ABC, abstractmethod

from app.config import get_settings

logger = logging.getLogger(__name__)

# FastAPI static mount prefix for generated images (kept in sync with app/main.py).
IMAGE_URL_PATH = "/images"


def build_image_prompt(prompt: str) -> str:
    """Build the instruction sent to an image model."""
    return (
        "Create a vibrant, professional marketing promotional image for this "
        f"campaign: {prompt.strip()}. Eye-catching, high quality, no text overlays."
    )


def save_image_bytes(data: bytes, prompt: str) -> str:
    """Persist generated image bytes locally and return a servable URL."""
    settings = get_settings()
    os.makedirs(settings.image_storage_dir, exist_ok=True)

    slug = re.sub(r"[^a-z0-9]+", "-", prompt.lower()).strip("-")[:40] or "campaign"
    filename = f"{slug}-{uuid.uuid4().hex[:8]}.png"
    path = os.path.join(settings.image_storage_dir, filename)
    with open(path, "wb") as handle:
        handle.write(data)

    base = settings.public_base_url.rstrip("/")
    return f"{base}{IMAGE_URL_PATH}/{filename}"


class ImageProvider(ABC):
    """Generates a marketing image URL from a campaign prompt."""

    name: str = "base"

    @abstractmethod
    def generate_image_url(self, prompt: str) -> str:
        """Return a URL to an image generated from ``prompt``."""
